# Some constants that are vital to the simulation

STARTING_POPULATION = 300
POPULATION_LIMIT = 660
POPULATION_MINIMUM = 300
REPRODUCTION_WAIT_PERIOD = 10

INPUT_NODES = 15
HIDDEN_NODES = 9
OUTPUT_NODES = 3

PASSIVE_ENERGY_GAIN = 5

ZONE_SIZE = 30
ENVIRONMENT_ZONE_SIZE = 60
QUADTREE_CAPACITY = 2