# Some constants that are vital to the simulation

STARTING_POPULATION = 300
POPULATION_LIMIT = 999
REPRODUCTION_WAIT_PERIOD = 10
ORGANISM_INTERACTION_LIMIT = 15

INPUT_NOTES = 15
OUTPUT_NODES = 3

PASSIVE_ENERGY_GAIN = 5